# ##############################################################################
# The contents of this file are subject to the PyTis Public License Version    #
# 1.0 (the "License"); you may not use this file except in compliance with     #
# the License. You may obtain a copy of the License at                         #
#                                                                              #
#     http://www.PyTis.com/License/                                            #
#                                                                              #
#     Copyright (c) 2018 Josh Lee                                              #
#                                                                              #
# Software distributed under the License is distributed on an "AS IS" basis,   #
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License     #
# for the specific language governing rights and limitations under the         #
# License.                                                                     #
#                                                                              #
# @auto-generated by the PyTis Copyright Tool on 06:01 03 Mar, 2018            #
############################################################################## #
#


from __init__ import Service

class BitcoinAverage(Service):

	name = "BitcoinAverage"

	def setup(self):
		Service.setup(self)
		print ('prefect')

		
	def run(self):
		print("%s.run(self) -- called" % self.name)
		#self.log.error (self.name)

		#self.log.error(repr(self))


